// isAutoGenerated.js
function isAutoGenerated(title) {
    // Check if the title contains the flag "Auto-generated" (case-insensitive)
    return title.toLowerCase().includes('auto-generated');
}

module.exports = { isAutoGenerated };
